### ISSUE TITLE
Powered Minecart Implementation

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#107]
Not implemented, as there's a scenario where it get's stuck in a teleport loop between two portals. This comes from the direction where it's pushing not being changed

**Comment by Pheotis** [comment]
This was mostly implemented in 852ac1e
The only problem is that powered momentum is not maintained.

Even though there is enough fuel, and even though we provide enough velocity, the minecart still grinds to a stop.
The only way to fix this is to modify `xPush` and `zPush`; neither of these are exposed in the paper or spigot APIs.

This will need to be resolved via an API-level pull request.
The candidate PR can be found [here](https://github.com/PaperMC/Paper/pull/7548).

**Comment by Pheotis** [comment]
Per the above, Knarvik's PR has now been added to Paper.

All that's left now is implementing a PushX / PushZ boost on minecarts on our end.
For paper 1.18.1+, this should be used.

For <=spigot || <=1.18.0, should just keep the existing implementation.
It works, it is just not quite as seamless.
