### ISSUE TITLE
Assorted SQL Issues

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#114]
During SG-Rewritten's development, we primarily tested via SQLite (while trying to make an effort to make sure that all used syntax was also valid in MySQL).

Unfortunately, upon preliminary testing, some of the newer database code is slightly incompatible with MySQL.

Additionally, there appear to be some problems with modern inter-server portals.

This issue will be used to keep track of all current SQL debugging, the issues found as a result of those efforts, and our work towards correcting them.

## Known Problems:
- [x] `nullable` MySQL incompatibility.
- [x] Multiple issues with foreign keys
- [x] A stack trace caused by interserver portals (found by Thorin -- TBP)

**Comment by Pheotis** [comment]
- A `nullable` compatibility problem related to this issue was solved in commit 3e0c0a1d0f77d5399f3a675a43191a2828611aeb

**Comment by Thorinwasher** [comment]
Most of these issues stems from invalid use of the foreign key. I'm not good at sql, but sqlite allows for behaviors that might cause bugs, whil mysql throws an stacktrace instead.

**Comment by EpicKnarvik97** [comment]
I've fixed some bugs in cf0c0f4, 56aca59 and c8353d0, but I'm not sure if it fixes any of the mentioned bugs.

**Comment by Thorinwasher** [comment]
This is a somewhat general issue, but:
- All unit tests work fine now
- No stacktraces are run when creating a interserver portal
