### ISSUE TITLE
Control Surface Management

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#122]
Although there are none added by default, the core plugin will nonetheless have the mechanisms in place to facilitate add-ons that add extra flags or controls.

This issue will be used to track implementing that.

**Comment by Pheotis** [comment]
This conversation expanded from issue #121

**Comment by EpicKnarvik97** [comment]
After a lot of discussion, the easiest and most powerful solution seems to expand the create event. By allowing add-ons to consume control blocks and specify if an activator has been added, it's possible to allow add-ons to manage control blocks as needed, without it interfering with normal functionality. By adding a new portal position type for these add-on controls it's possible to ensure protection and prevention of collisions, while at the same time making sure they aren't treated as normal signs or buttons.

The main feature of this approach is that the core Stargate plugin can stay completely blind to add-ons in use.

We must make sure un-recognized flags are kept or sent during the create event to allow the relevant events to do whatever they need to do.

**Comment by Pheotis** [comment]
- [x] API that allows addons to register and access gate flag status.
- [ ] API that allows addons to claim an additional control surface.

The latter item appears not to be necessary for parity, so that can probably wait until 1.5.0.0
