### ISSUE TITLE
Make input filter stricter

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#128]
Currently, spaces can be used before and after any name.

This may cause typos and confusion.
https://i.imgur.com/CDPpZVb.png

**Comment by Pheotis** [comment]
General formatting checks are mostly done; the final thing left to do before closing #128 is to find a way to limit Unicode.
The best approach I can think of is to filter out characters which are neither Latin nor part of the target locale.

Surprisingly, from the look of things, no public library capable of accomplishing this currently exists.
A lang-script bridge filter would be useful for many other projects; it is probably best to separate this from SG.

A public library in a separate repo would be ideal; to that end, I have created one [here](https://github.com/stargate-rewritten/Language-Linter).

**Comment by Pheotis** [comment]
The urgent portion of this issue has been resolved.
The remainder is [langlint]([here](https://github.com/stargate-rewritten/Language-Linter), which has become a project in its own right.

Going to close the portion of this issue pertaining to 1.0.0.5.
A new issue will be needed in future to track implementing langlint.
