### ISSUE TITLE
Silent Protection of Portals

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#130]
When an unauthorised user attempts to break a portal, it doesn't work (the break event is cancelled).

Having said that, the user is not informed *why* they were unable to break the block in question.

Should we print `conflictPerms` on this event?

**Comment by Thorinwasher** [comment]
@Pheotis What I know this is what is done in the legacy version. I don't know whether printing a perms message or not is necessary or not

**Comment by Pheotis** [comment]
The existing behaviour worked in legacy, and is somewhat intuitive; as such, by default, it should probably remain.
That said, I can see circumstances wherein someone may want to enable an error message for block protection.

Having said that, I don't think this is something most people would be interested in using.
As such, going to merge this with issue #96, should we want to reopen that in future.
