### ISSUE TITLE
Probable Permission Default Problem

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#144]
Likely relating to existing permission handling -- see issue #117.
Reported by ert on [discord](https://discord.gg/mTaHuK6BVa).

![image](https://user-images.githubusercontent.com/49039536/160259340-e9dab8f5-c08d-4f84-9907-f1f965015a91.png)

In alpha `1.0.0.1`, such behaviour would print the teleportation message.
In alpha `1.0.0.4`, that behaviour no longer occurs.

Spigot 1.18.2 on windows 10.

**Comment by Pheotis** [comment]
Reproduced on Spigot/CraftBukkit `1.18.2` API `1.18.2-R0.1-SNAPSHOT`.
This issue seems to exclusively occur with certain permission handlers.

This issue only reproduces for players other than the gate's owner.
Sign interactions work normally; gate connects properly, activation works.
non-op'd players entering gate are rejected to entry portal with a `\n`.

Going to investigate further into the exact circumstances.

**Comment by Pheotis** [comment]
Reproduces on Paper.
I can now confirm that this is a conflict between [Vault](https://github.com/milkbowl/Vault) and [GroupManager](https://github.com/ElgarL/GroupManager/).

This only occurs when all three jars (stargate, groupManager, and Vault) are present.
Removing either GroupManager or Vault stops this problem from occurring.

# Reproduction Steps:
1. Start a paper instance with paper, vault, stargate, and group manager.
2. As an op'd player, make a gate on the central network.
3. As an op'd player, make a gate on the same network, this time thousands of blocks away.
4. As that op'd player, scroll through, activate, and enter the portal; it will work.
5. As a separate, un-op'd, player, scroll through, activate, and enter the portal; it will fail.
6. No reason for failure printed; all activations work fine -- the player is simply returned to their origin with ` \n` in chat.

**Comment by Thorinwasher** [comment]
This was solved during the refactor related to issue #119
