### ISSUE TITLE
Legacy Bungee Gate Behaviour [TMS 222180]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#164]
1. Legacy bungee gates do not check if there exists a valid destination gate prior to sending the user across servers.
2. Even if a destination legacy bungee gate exists on the receiving server, the legacy bungee gate will ignore that destination and teleport the user to wherever they were when they last were on the receiving server (if first time visiting, that is spawn).

## Environment
Sending
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating Knarvik 0.9.3.7, Test Environment unit `2-Paper-Offline-MigKnar-Modern-SQL`)
**Server Version**: `git-Paper-350` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`
Via
**Proxy Version**: `git-Waterfall-1.18-486`
To
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating simulated 1.0.0.2 config, Test Environment unit `2-Spigot-Offline-MigOld-Modern-SQL`)
**Server Version**: `3491-Spigot-b081915-95d233d` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`

## Details
![image](https://user-images.githubusercontent.com/49039536/170841813-02dff4d3-d2c3-4c64-8533-46b392a2421c.png)
This example does not send the player to gate 1 on server SGKnarvik (although said gate exists)
Instead it sends the user to the location where they last logged out on SGKnarvik.

# Also
Legacy Bungee Gates are impossible to create when the server name exceeds the number of characters available on the sign.
Might it be better to instead have the user type the first `n` characters of the receiving server and try to match them?

**Comment by Thorinwasher** [comment]
An answer to point 1: It's literally impossible to know if the gate exist on the other server.

**Comment by Pheotis** [comment]
That's fine; that said, if the gate exists, it should probably teleport the user there.
If the gate does not exist, it should teleport the user to where they last logged off, and print `bungeeInvalidExitGate`

**Comment by Thorinwasher** [comment]
This might relate to issue #166

**Comment by Thorinwasher** [comment]
#180 Solves this issue
