### ISSUE TITLE
Networked Exit Behaviour [TMS 222187]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#169]
When a user opens a networked portal, it will open the iris of the exit gate.
If the user goes through that exit before they go through the entrance, it will result in an invalid destination error.

Is this intended behaviour?
Perhaps a more clear localization message may be in order.

Possibly related to #160 
![image](https://user-images.githubusercontent.com/49039536/170845907-c6c2647c-1167-4675-9101-cda849207e50.png)

**Comment by Thorinwasher** [comment]
This is intended behavior, as the destination of the teleportation would otherwise be unclear for the end user if they went from the exit

**Comment by Pheotis** [comment]
Makes sense.
Think it is worth improving the error message?

**Comment by Thorinwasher** [comment]
We could probably add another message, if that improves something

**Comment by Pheotis** [comment]
How about `tpOccupied` "Another player is currently using this portal; try again in a few moments!"?

**Comment by Thorinwasher** [comment]
Sure! sounds like a plan
