### ISSUE TITLE
Incorrect Translatable Message [TMS 222189]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#171]
When a player lacks the sg.create.network.custom.<name> permission
And tries to create a portal on the <name> custom network,

They receive `faultExists`.
This should result in `faultNetwork`.

(If they create the same portal with the required permissions, it will work as intended)
![image](https://user-images.githubusercontent.com/49039536/170846043-cb9552e7-a5c8-4c85-a5d2-5c13e3a692bb.png)

**Comment by Thorinwasher** [comment]
If the player lacks permission to create in a custom network, it will try to create it in a personal network, Are you sure you did not have a duplicate named portal in the personal network.

If the player has the ´sg.admin.bypass.private´ node, then it will create it in a personal network for the player with the same name as the custom network name.

Could you try to replicate this in a new world with nothing else  in it? (I don't get similar behavior)

**Comment by Pheotis** [comment]
That makes sense; given that I was numbering portals, there was almost certainly a duplicate gate on the personal network.
This behaviour is intended... that said, it is not intuitive per se.

Might be worth improving the message received. 
Do you think we could do three messages, all as errors?

`faultNetwork` followed by `gateCreatePersonal` followed by `faultExists`?
(`faultExists` can be omitted whenever there is not a duplicate gate on the personal network).

**Comment by Thorinwasher** [comment]
So maybe have a message tells you this (but better worded)
> [Stargate] You're lacking perms to create network ({netname}), changing to it's personal equivalent

**Comment by Pheotis** [comment]
how about `gateCreateFallback` "Unable to create your gate on the %network% network; trying your personal network instead!"?
