### ISSUE TITLE
Inconsistent Interdimensional Ghost Gates [TMS 222189]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#172]
In unknown circumstances, when creating  fixed interdimensional portals, gate creation can fail spectacularly.
The result is a ghost portal (in the nether)... reproduction has thus far been unsuccessful.

Behaviour:
- When activating the ghost, the result is faultDestination
The ghost in the nether:
![image](https://user-images.githubusercontent.com/49039536/170846473-ed756299-dedb-4ecc-ba91-dc74017bf61f.png)

- When attempting to access the ghost from a networked portal in the same dimension, the result is either the closet vanilla nether portal in the overworld, or the ghost portal. (unknown circumstances -- appears to be random).
Accessing from networked gate in the nether:
![image](https://user-images.githubusercontent.com/49039536/170846488-14ee194d-d1bc-441f-9274-89aa9fbebbd4.png)

- When accessing the ghost from a direct portal in the overworld, one exits from the ghost portal.
![image](https://user-images.githubusercontent.com/49039536/170846518-77de3c03-c4db-4fe7-b7d4-5d487c497e50.png)

- When accessing the ghost from a networked portal in a different dimension, the result is the ghost portal.
![image](https://user-images.githubusercontent.com/49039536/170846548-287b7866-2242-4cc9-987f-a7a5ec2ff6dd.png)

# Environment:
**Plugin Version**: `ALPHA-1.0.0.4` (Fresh Installation, Test Environment unit `3-Spigot-Online-MigNew-Modern-SQLite-Addons`)
**Server Version**: `3491-Spigot-b081915-95d233` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`

## Repro steps:
Unknown.

**Comment by Thorinwasher** [comment]
Does this persist if you reboot the server, in that case do you have a database with the portal in it?

**Comment by Pheotis** [comment]
I no longer have the server instance wherein this occurred.
I have attempted to reproduce this several times and have been unable to.

**Comment by Pheotis** [comment]
Actually, for that reason alone I will decouple this from the 1.0.0.6 milestone.
If this doesn't reproduce in the next month, we can close this as CNR.

**Comment by Pheotis** [comment]
Closing as CNR.
