### ISSUE TITLE
Presets are lacking custom network permissions[TMS 222190]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#173]
When creating a network as an online user (in this case, Pheotis, with `sg.preset.moderator` set to true);

Creating the following portal:
```
3

t7

```

will result in this personal gate.
![image](https://user-images.githubusercontent.com/49039536/170846622-b807f7af-4ace-4da9-827b-4ae623c58677.png)

As the user t7 has not joined the server, and thus, as there is no {t7} network (nor a user lock), the result should be `(t7)`.

Attempting to force a custom portal fails as well, implying that there is a user lock where there shouldn't be one:
```
3

(t7)

```
![image](https://user-images.githubusercontent.com/49039536/170846672-7674bd74-f449-4ec7-a536-2a86fa2c9e1f.png)

It should be noted that it is considering this to be a personal gate directly -- i.e. is checking `sg.network.personal` instead of `sg.network.custom.name`

Even if this were not a parsing error, that is also a problem.
Should the permission not be something like `sg.create.network.personal.others.name`?

![image](https://user-images.githubusercontent.com/49039536/170846723-dbef7f14-3255-4073-ab81-e06e0a20b181.png)

Possibly related to #165?

**Comment by Pheotis** [comment]
[TMS 222192]

Update: this appears to be an issue with *ANY* custom name while under the sg.preset.moderator group.
```
29

portalTestNet
AQ
```
![image](https://user-images.githubusercontent.com/49039536/170846824-9c4cebd9-695c-49d5-b73c-e14b005ead57.png)
for instance, `portalnetTest`.

**This does NOT occur when the player is OP'd.**
```
 2b

portalTestNet
AS
```
![image](https://user-images.githubusercontent.com/49039536/170846863-b34905f3-bb49-44ad-837f-d66232598635.png)

**Comment by Thorinwasher** [comment]
I've looked into this:
The presets are lacking any permission regarding `sg.create.custom` and `sg.destroy.custom`. Might be a good idea to add that node into the builder preset or something like that

**Comment by Thorinwasher** [comment]
I'm still getting problems with generating proper child permissions for the `sg.create.custom` node
