### ISSUE TITLE
Gate ownership.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#184]
- [x] Nodes = `sg.*.owned`
- [x] Hidden config = `enableOwnedGates`
  - [x] Should be default
  - [x] Should be added to `sg.preset.gatemaker`

**Comment by EpicKnarvik97** [comment]
What exactly should happen when enableOwnedGates is disabled? Is it basically a way to disable any permission overrides for the portal's owner? And if so, isn't it kind of reduntant if it's also possible to disable by setting the correct permission nodes to false?

**Comment by Pheotis** [comment]
It is redundant, but as a hidden config, that doesn't really matter.
It was simple to add, and it gives users an option to simulate the behaviour of some 2015 forks.
Also slightly easier from a support response perspective than to explain the required negated nodes.
