### ISSUE TITLE
Player does not get charged when using gate

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#186]
How to replicate:
- set useEconomy: true
- set usageCost: 5

Use a gate that is not in your own personal network

Expected behavior:
- User gets charged 5
- User teleports
Behavior:
- User teleports

**Comment by EpicKnarvik97** [comment]
There is an additional issue with this fix. The return value of charge is not used, so a player can teleport even if the payment couldn't be processed.
