### ISSUE TITLE
Bungee portals not teleporting you properly to destination portal under certain circumstances

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#190]
how to replicate:
- Create the following portal in `server1`:
```
1
2
server2
u
```
- Create the following portal in `server2`:
```
2
3
server3
u
```
- Create the following portal in `server3`
```
3
1
server1
u
```
- Travel between the servers using the portals.

Behavior:
- Player does not get teleported to destination portal, but stays it it's previous position in the server

Expected behavior:
- Player gets teleported to destination portal

When restarting the server of the destination portal, this issue is fixed

**Comment by EpicKnarvik97** [comment]
Current tests have not been able to display any major change in portal data between its state after creation and its state after restarting the server.
It is possible this problem relates to the portal's reference to the legacy network in some way. It could be an ignored null value somewhere, or that two different legacy networks are created in some weird way.
