### ISSUE TITLE
Assorted Nitpicks [TMS]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#191]
Assorted minor nitpicks found via the current TMS sweep.
This will be edited over time.

- [x] [222175] Under Aesthetic Tweaks in the default config, the comment mentions that `GLOW_INK_SACK` is a valid colour modifier. That feature was removed.
  - ![image](https://user-images.githubusercontent.com/49039536/172395745-c9632185-d5c7-4c34-b497-ea007af05279.png)
- [x] [222176] Under the default config, running on the craft bukkit 1.18 TMS mock, the default text colour for birch signs is white.
  - ![image](https://user-images.githubusercontent.com/49039536/172394971-893e2c2b-6b05-48f1-93d5-0687ab0d44c5.png)
- [x] [222175] Both the supported languages list and the link should be updated.
  - I recall some new localisations having been added.
  - We are now using crowdin.stargate.thorinwasher.dev (although we should consider buying a domain eventually)
  - ![image](https://user-images.githubusercontent.com/49039536/172396628-e38b2935-d55f-412b-8f08-70da45b64e83.png)
- [x] [222179] Importing from Knarvik's fork prints a user-level warning... is this normal/intended?
  - ![image](https://user-images.githubusercontent.com/49039536/172397600-8de3035b-dfe1-47a5-949f-575383939230.png)
- [x] [222191] When a user creates a blank portal without central permissions, it should just default to the lowest network they have perms for (in this case, personal)
  - This error appears for the following portal:
> ```
> Name1
> Name2
>   
> flags
> ```
  - This error should only print if they try `(central)` or `central`
  - ![image](https://user-images.githubusercontent.com/49039536/172446823-9c8ff285-687e-48b2-ac17-72807bd06504.png)

**Comment by EpicKnarvik97** [comment]
Wait, so we don't support glowing signs at all anymore?

**Comment by Thorinwasher** [comment]
They kinda look odd, as we use Bungee chatcolors as coloring, while the glowing highlight depend on dyecolor. They might not match. But is this still a wanted feature?

**Comment by EpicKnarvik97** [comment]
> They kinda look odd, as we use Bungee chatcolors as coloring, while the glowing highlight depend on dyecolor. They might not match. But is this still a wanted feature?

It is a feature in my fork, together with being able to specify the colors used for every type of sign individually. I haven't experienced any weird-looking colors myself. In fact, some of the colors are quite nice:
![2022-06-07_15 49 14](https://user-images.githubusercontent.com/3597346/172396971-61acfcfe-0fd0-452a-8795-4f3efbac1100.png)
![2022-06-07_15 49 17](https://user-images.githubusercontent.com/3597346/172396987-77fe7d9e-a6ff-4060-909c-e869f2b37a51.png)
![2022-06-07_15 49 24](https://user-images.githubusercontent.com/3597346/172396995-ac068aa4-e437-4c94-8b84-4d54195f4c1e.png)

**Comment by Thorinwasher** [comment]
Okay, so that's a thing then

**Comment by Thorinwasher** [comment]
> * [ ]  [222179] Importing from Knarvik's fork prints a user-level warning... is this normal/intended?
>   
>   * ![image](https://user-images.githubusercontent.com/49039536/172397600-8de3035b-dfe1-47a5-949f-575383939230.png)

What logging level do you have in the config, is it Levlel.FINE?

**Comment by Pheotis** [comment]
> > * [ ]   [222179] Importing from Knarvik's fork prints a user-level warning... is this normal/intended?
> >   
> >   * ![image](https://user-images.githubusercontent.com/49039536/172397600-8de3035b-dfe1-47a5-949f-575383939230.png)
> 
> What logging level do you have in the config, is it Levlel.FINE?

Was mostly just wondering if that error was an issue or not.
If it could be an issue, the current log level is fine.
if it isn't an issue, FINE is probably a better level.

**Comment by Thorinwasher** [comment]
It's not an issue, I meant that this "error" will get thrown if you have debugging enabled

**Comment by EpicKnarvik97** [comment]
If the error says `Index already exists`, there is no problem. If it says anything else, there is a problem. It's a consequence of the lazy handling of duplicate indexes.
It is potentially an issue, but not necessarily.

It already has/is Level.FINE.

This is not a specific issue to my fork. It's printed every time createTables() is run after the first run.

**Comment by Pheotis** [comment]
> If the error says `Index already exists`, there is no problem. If it says anything else, there is a problem. It's a consequence of the lazy handling of duplicate indexes. It is potentially an issue, but not necessarily.
> 
> It already has/is Level.FINE.
> 
> This is not a specific issue to my fork. It's printed every time createTables() is run after the first run.

Ah, I forgot that the instance was already running at Level.FINE
That makes the 4th item a total non-issue; going to mark that part as resolved.

**Comment by Thorinwasher** [comment]
When applying glow ink to the sign, should the portal revert to black as its color // remove default coloring?

**Comment by EpicKnarvik97** [comment]
> When applying glow ink to the sign, should the portal revert to black as its color // remove default coloring?

If it's dyed, it should just have the highlighted version of the dye. If it's not though, you could either force the color to black or display it as-is, though it becomes kind of unreadable if highlighted and not dyed. I guess the hightlighting itself is trying to highlight black no matter which color we display.

Users must be able to use INC_SAC as well, to remove the dye.

**Comment by Thorinwasher** [comment]
>  I guess the hightlighting itself is trying to highlight black no matter which color we display.

Exactly. It can for example look like this:
![image](https://user-images.githubusercontent.com/37477983/172610102-645aa8a6-3170-4389-aef0-824e75588d3b.png)

So here the sign is colored black, which makes it go to the default coloring which in this case is light blue. It would be better if the line drawer defaulted back to this:
![image](https://user-images.githubusercontent.com/37477983/172610693-abc77f53-8672-4f1e-ae55-a26752f596c7.png)

**Comment by EpicKnarvik97** [comment]
> > I guess the hightlighting itself is trying to highlight black no matter which color we display.
> 
> Exactly. It can for example look like this:
> 
> So here the sign is colored black, which makes it go to the default coloring which in this case is light blue. It would be better if the line drawer defaulted back to this:

For my fork, I used the inverse of the dye color for the highlighting, which generally gives some quite nice colors, especially for glowing signs. Could we add that behavior, or at least make it an option?

```java
/**
     * Inverts the given color
     *
     * @param color <p>The color to invert</p>
     * @return <p>The inverted color</p>
     */
    public static Color invert(Color color) {
        return color.setRed(255 - color.getRed()).setGreen(255 - color.getGreen()).setBlue(255 - color.getBlue());
    }

    /**
     * Gets the chat color corresponding to the given color
     *
     * @param color <p>The color to convert into a chat color</p>
     * @return <p>The resulting chat color</p>
     */
    public static ChatColor fromColor(Color color) {
        return ChatColor.of(String.format("#%02X%02X%02X", color.getRed(), color.getGreen(), color.getBlue()));
    }
```

**Comment by Thorinwasher** [comment]
That would be interesting! Let's see the current options in this version.
```yaml
signStyle:
  defaultForeground: BLACK
  defaultBackground: WHITE

  # [1: foreground, 2: gate type, 3: grey, 4: background]
  pointer: 2

  # [1: selected gates coloured, 2: all gates coloured, 3: no gates coloured]
  listing: 2
```
So if we have pointer option number 4, then do the inversion thing for the pointers, if the sign is not black with default coloring

**Comment by EpicKnarvik97** [comment]
That could work. I really love some of the contrasts it creates, so I don't want to lose it for my server.

**Comment by Thorinwasher** [comment]
For the language point on this thread. It might be a good idea to push that until alpha release

**Comment by EpicKnarvik97** [comment]
Also for [222175], should the displayed languages always use the full language codes (nb-NO, en-US), or should the shortcuts (en, nn) be used whenever available?

**Comment by Pheotis** [comment]
> Also for [222175], should the displayed languages always use the full language codes (nb-NO, en-US), or should the shortcuts (en, nn) be used whenever available?

Shortcuts should be used whenever available.

Anyways, as that nitpick is a formatting issue, probably best to delay dealing with that until the alpha release in case any new language translations come in.

As such, I think it is safe to close this issue now.

**Comment by Pheotis** [comment]
Going through an end_portal results in an advancement.
Can this be suppressed?

![image](https://user-images.githubusercontent.com/49039536/173656551-67e4ae4c-e0dc-40ff-8546-632266b714a6.png)
[TMS 222179]

**Comment by EpicKnarvik97** [comment]
It seems `PlayerAdvancementDoneEvent` exists in the API, but it cannot be cancelled, and it doesn't seem like it can be modified.

Paper has an event that might be used: https://github.com/PaperMC/Paper/pull/978
