### ISSUE TITLE
`A` gate iris blocks do not break with explosions [TMS 222194]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#195]
When an always on portal is destroyed in an explosion, and `destroyOnExplosion` is true, the traversable blocks do not appear to be removed when the gate is deleted.

This was tested for `end.gate`.
![image](https://user-images.githubusercontent.com/49039536/172448486-2884f72b-7c1b-43a9-aad8-c4e0c701d806.png)

**Comment by EpicKnarvik97** [comment]
Are end gateway blocks actually destroyable? You should probably test with wool or something to see if it's our protection or the built-in protection which protects the iris.

**Comment by Pheotis** [comment]
End gateway blocks are not naturally destroyable (at least not via explosions)
A simple nether portal's iris gets destroyed by the tnt itself.

That said, iris blocks are not part of the structure the player placed.
When the gate is getting deregistered because of the explosion, the plugin should delete any active iris blocks.

Otherwise, we are giving players an infinite way to generate the blocks contained within the iris and/or to use them in builds.
If the iris is valuable, or unplaceable, such behaviour could become problematic.

**Comment by EpicKnarvik97** [comment]
Then we should probably prevent any items from dropping from any of the iris blocks as well.
Either by checking if there is a way of disabling drops, or perhaps by removing the entrance blocks before the explosion event is executed.
