### ISSUE TITLE
Spigot furnace minecarts [TMS 222197].

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#196]
1. When on the latest version of spigot
2. When a mob chain including a furnace minecart is teleported through a gate,

1. The furnace minecart splits from the chain
2. Its teleportation is cancelled
3. Movement is not restored.

![image](https://user-images.githubusercontent.com/49039536/172450709-9143668a-a82a-42b9-8796-1a6d14c93fdf.png)

This is partially intended; spigot does not support PushX/PushZ.
Not sure if the teleportation cancellation is part of that intended behaviour though.

We have the capacity to teleport the minecart; we just lack the ability to move it after teleporting;
Would it not make more sense to avoid splitting the entity, and instead teleport it (with no restoration of momentum thereafter?)

**Comment by Thorinwasher** [comment]
It is indeed part of the intended behavior, as it can create an infinite teleportation loop otherwise

**Comment by Pheotis** [comment]
Nitpick: this behaviour repros on paper.

Normal furnace minecarts teleport properly and restore their momentum. This behaviour only occurs when the furnace minecart has passengers.

**Comment by Pheotis** [comment]
Update: almost certainly an independent issue contained within #225.
Closed as duplicate.
