### ISSUE TITLE
Interdimensional Water Iris Updates [TMS 222198]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#197]
When broken by the player in certain unknown circumstances, active traversable iris blocks from interdimensional fixed always on gates will fail to delete.

Thereafter, they will be subjected to physics.
![image](https://user-images.githubusercontent.com/49039536/172451867-2f7d48cc-ca11-4a1e-9823-6edd42fcc2c2.png)

**Comment by Thorinwasher** [comment]
The commit above might fix this issue, I'm not certain

**Comment by Thorinwasher** [comment]
Tested and fixed. This is a replicate of issue #195
