### ISSUE TITLE
Invalid economy handling during creation if name is invalid

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#204]
Player gets charged money by creating a gate if a gate by that name already exist. This might be a larger issue than only this; some other cancellations might have the same effect

**Comment by EpicKnarvik97** [comment]
This is because the payment happens before the portal is added, but if the player cannot pay, they shouldn't be able to create it.
One way to solve this would be to verify the name before taking payment.

**Comment by Thorinwasher** [comment]
So, we should probably move permission checks and such to the end, right before portal gets added
