### ISSUE TITLE
Fire is not handled properly

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#205]
How to reproduce:
- make a wool gate
- light it using flint and steel

Behavior:
- The wool catches fire and disappears
- the gate still functions normally

expected behavior:
- Either to not let a gate catch fire, or to destroy the gate if it has been burnt

**Comment by Pheotis** [comment]
Fire is able to be ignited on and/or spread to, the blocks above and below the sign.
Fire can also be ignited on and/or spread to, the top of the portal.

In no known circumstance will the portal blocks burn.
Apart from this, fire is blocked as intended.

Environment: CB 1.19 running latest sg
Dev environment: see artifact 1. [TMS 222 176]

**Comment by Thorinwasher** [comment]
Probably fixed
