### ISSUE TITLE
Verification on NMS/MCA Updates

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#208]
As a supplement to #207 we should probably intensively verify areas where nms or mca changes are detected.
The easiest solution is probably https://github.com/bergerhealer/BKCommonLib-RegionChangeTracker

Plugins known to conflict with stargate without throwing the relevant events:
- Treemod #265

**Comment by Thorinwasher** [comment]
Fixed with 62c1f06821c7e99e1dfb26f01dea4fd06a621083
