### ISSUE TITLE
Instant Sign Failure [TMS 222 179]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#209]
![image](https://user-images.githubusercontent.com/49039536/173636229-8428f61a-e9da-4cd9-9d9c-03ec91e3f75e.png)
When running 1.15 spigot, on a migrated version of the most recent legacy config, it is impossible to create a new gate, regardless of permissions.

Signs placed are instantly broken, with the reason of INVALID_NAME.
Vault Four.

<details> 
  <summary>Instance Trace</summary>
https://pastebin.com/iJgxxwiT
</details>

**Comment by Thorinwasher** [comment]
I tested this on your instance provided in vault 4. Can not reproduce on a 1.15 client, are you sure its not something to do with a 1.19 client incompatibility for 1.15 or something?

The reason why the message INVALID_NAME gets sent, is because the signs first row is empty. Every portal has to have a name, which is the first row

**Comment by Pheotis** [comment]
> I tested this on your instance provided in vault 4. Can not reproduce on a 1.15 client, are you sure its not something to do with a 1.19 client incompatibility for 1.15 or something?
> 
> The reason why the message INVALID_NAME gets sent, is because the signs first row is empty. Every portal has to have a name, which is the first row

The sign's first row was empty because it was impossible to enter any text on the signs before they were instantly broken.
Anyways, I am going to try and repro this on my end with vault 4. If this doesn't repro, we can safely close this as CNR.

**Comment by Thorinwasher** [comment]
I can confirm that this only happens for 1.19 clients using bungee. This is most definitely an issue with waterfall conversion for 1.19 clients to a 1.15 server and not a problem on our end

Same behavior can be seen for ´#standing_signs´

**Comment by Pheotis** [comment]
This was a protocol hack issue.
[ViaVersion#2935](https://github.com/ViaVersion/ViaVersion/issues/2935)
