### ISSUE TITLE
Console sg command inconsistency [TMS 222181]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#210]
When running a 1.15 spigot version, on console, the sg command lists other sg commands.
When running a modern spigot version, the sg command returns the sg version as expected.

This behaviour should probably be consistent (i.e. typing `sg` into older instances should also return the plugin version string.

![image](https://user-images.githubusercontent.com/49039536/173694381-4cdeca17-ab6c-4ef1-bec7-58a2d5a1e8b3.png)

> edit: this appears to occur when using *any* console command on 1.15 versions of the plugin; instead of functioning, any command that starts with /sg will print the following:
> `[17:44:13] [Server thread/INFO]: /sg - Prints the version of StarGate the server is running.
[17:44:13] [Server thread/INFO]: /sg about - Provides a link to StarGate's documentation./sg reload - Used to reload the plugin.`

**Comment by EpicKnarvik97** [comment]
This is a weird one. For modern Spigot, No arguments are supplied and thus the info message is displayed. For Spigot 1.15, Spigot gives an argument in the onCommand call which is not a valid argument. Thus the explanation of the command, as defined in plugin.yml is displayed.
You are certain there was no space or other character after /sg on Spigot 1.15, right? It could either be a user-error, or Spigot 1.15 sending a list with some unknown argument for some unknown reason.

**Comment by Pheotis** [comment]
> This is a weird one. For modern Spigot, No arguments are supplied and thus the info message is displayed. For Spigot 1.15, Spigot gives an argument in the onCommand call which is not a valid argument. Thus the explanation of the command, as defined in plugin.yml is displayed. You are certain there was no space or other character after /sg on Spigot 1.15, right? It could either be a user-error, or Spigot 1.15 sending a list with some unknown argument for some unknown reason.

I have tried this again with no space after /sg.
This appears to have been user error.

That prints for everything which is not a valid command, including "/sg " and "/sg *".

I did discover a few nitpicks though:
 - There is no \n before `/sg reload`
 - There is no mention of `/sg trace`.
 - There is no mention of `/sg version.`
