### ISSUE TITLE
Assorted I Gate Problems [TMS 222 181]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#212]
1. Once created and/or destroyed,
  For any interserver (`I`) portal:
   - The portal will not react and/or function unless another player is online on the destination server
   - Once a player does join the destination server, an infinite portal ID loop occurs on console.
![image](https://user-images.githubusercontent.com/49039536/173702201-c044189c-5c05-495a-9e75-ebff91f0e84a.png)
2. For any portal ID or network caught in the portal ID loop, it will be impossible to create, access, and/or destroy said portal.
3. The signs for portals stuck in such loops will not regenerate their text when broken.
  - shift right clicking the signs does nothing. 
![image](https://user-images.githubusercontent.com/49039536/173702101-85608eae-0d2f-4965-8ee1-8f3a89805efd.png)

**Comment by Thorinwasher** [comment]
What server was this on?

**Comment by EpicKnarvik97** [comment]
This is no id loop. Read the console.
What happens is that when an inter-server portal is destroyed, it sends a PORTAL_REMOVE message. When the message is received, the same method is used to destroy the portal, which triggers a PORTAL_REMOVE message back to the other portal.

Casting the network to a local network when receiving the PORTAL_REMOVE message (StargateBungeePluginMessageListener line 163) might fix this.

**Comment by EpicKnarvik97** [comment]
It not functioning without another player is an expected bug if using SQLite. The only way to know if a portal is connected to anything is to wait for plugin messages to synchronize the inter-server network. If a player is missing from one of the servers, plugin messages cannot be sent, thus the portal assumes its destination does not exist.

**Comment by Pheotis** [comment]
> What server was this on?

This was on both of the 1.19 test instances within set two of the test environment.
The instances were MySQL-connected, on windows, running behind a waterfall proxy.

**Comment by EpicKnarvik97** [comment]
> This was on both of the 1.19 test instances within set two of the test environment. The instances were MySQL-connected, on windows, running behind a waterfall proxy.

I guess, while MySQL shares the database, making easier sharing of the inter-server network possible, the inter-server network is never fetched again from the database, making it too. reliant on Bungee messages.

It would technically be possible to continously fetch inter-server portals from a shared database and disable the plugin messaging (for portal sharing) when a shared database is used for all connected servers. Still wouldn't help for SQLite though.

**Comment by Thorinwasher** [comment]
> It not functioning without another player is an expected bug if using SQLite. The only way to know if a portal is connected to anything is to wait for plugin messages to synchronize the inter-server network. If a player is missing from one of the servers, plugin messages cannot be sent, thus the portal assumes its destination does not exist.

Weirdly enough, this is not a problem as bungee coord stores all messages it could not send and sends them instantly to the server when it can (when a player joins). Servers being empty off players should not matter, as a portals functionality only matters when a player is online: Interserver networks should in theory work exactly as smooth as normal networks

**Comment by EpicKnarvik97** [comment]
> Weirdly enough, this is not a problem as bungee coord stores all messages it could not send and sends them instantly to the server when it can (when a player joins). Servers being empty off players should not matter, as a portals functionality only matters when a player is online: Interserver networks should work exactly as smooth as normal networks

The problem here is that the inter-server portal has no destination until a player joins the target server, thus making it impossible to travel to the target server and let it fix itself.

If the player could go through the portal there would be no problem, unless the destination was actually invalid.
We could go the route of legacy bungee and assume the target exists, but that would partly ruin the point of the new system.

**Comment by Thorinwasher** [comment]
> The problem here is that the inter-server portal has no destination until a player joins the target server, thus making it impossible to travel to the target server and let it fix itself.

Could you explain that in different words, I think I'm misinterpreting it. Like it's fetching the whole network including destination from a shared database on startup (also why this feature is not available for SQLite). The bungeecoord messages are only there to keep the list of portals dynamically updated

**Comment by EpicKnarvik97** [comment]
> Could you explain that in different words, I think I'm misinterpreting it. Like it's fetching the destination from a shared database on startup (also why this feature is not available for SQLite). The bungeecoord messages are only there to keep the list of portals dynamically updated

I think I'm mistaken, as this thing confuses me.
I can think of edge cases for SQLite though, where we will get problems because of incomplete synchronization of inter-server portals, such as portals created on one server while the others are offline.

I think this needs to be re-tested with the fix to see if there is actually another problem. I'm not sure exactly which context caused the portal to be marked as invalid, so it could be a non-issue.

**Comment by Thorinwasher** [comment]
I tested it with the fix. And it seems like no PORTAL_ADD request is not sent anymore. I'll look into it
