### ISSUE TITLE
Nitpick: Error Catching

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#219]
When running upstream of paper, when logging at an info level, the remote gateway catch prints an error to console.

Can we catch it?
```md
[Stargate] Plugin Stargate v1.0.0.9-ALPHA has failed to register events for class net.TheDgtl.Stargate.listener.PlayerAdvancementListener because com/destroystokyo/paper/event/player/PlayerAdvancementCriterionGrantEvent does not exist.```

**Comment by Thorinwasher** [comment]
No, but we can just check if paper is implemented or not. (I honestly just forgot to fix that)
