### ISSUE TITLE
Nitpick: Portals Folder

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#221]
On certain migration instances (see the MigLeg and MigKnar test environments), the `portals` folder persists.

This folder was used in legacy, but isn't used in SGR.
Should probably be handled in some way (deleted)?

**Comment by EpicKnarvik97** [comment]
If some portals failed to migrate, the portal folder must persist, or their data must be stored in another file instead.

**Comment by Pheotis** [comment]
I think the name "Portals" is misleading for that purpose;
perhaps we can rename the folder "Archives" or something similar?

**Comment by EpicKnarvik97** [comment]
Or perhaps Legacy Data? We could put any invalid gate formats there as well.
