### ISSUE TITLE
Nitpick: Purple

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#223]
Traversable `END_GATEWAY` blocks will return if broken from within the iris of a protected `A` gate. This is intended.

Unfortunately, the `END_GATEWAYS` are not the only things that return;
Their purple beacon things return as well.

Is there any way we can make sure that those things stay suppressed? 

![image](https://user-images.githubusercontent.com/49039536/174674175-742d870c-7cc4-4f3e-94ba-9cc14621766d.png)

**Comment by EpicKnarvik97** [comment]
If the problem is that they are kind of refreshed when the blocks are broken, but the block break event is cancelled, we could listen for a cancelled block break event related to END_GATEWAY inside a portal iris and re-apply the age.

**Comment by Thorinwasher** [comment]
I can not replicate this on 1.18.2, or 1.15. I can only replicate this on 1.19 instances (craftbukkit, spigot, paper). My bet is that this is a craftbukkit 1.19 related issue

**Comment by Pheotis** [comment]
[SPIGOT-7076](https://hub.spigotmc.org/jira/browse/SPIGOT-7076)
