### ISSUE TITLE
Leashed entitites with a passenger throw an error/exception when teleporting to the nether

### ISSUE THREAD

**Issue by EpicKnarvik97** [stargate-rewritten/Stargate-Bukkit#226]
There is a bug which occurs when holding some entity in a leash which has another entity as a passenger, and entering a Stargate going to the nether. For example, connecting a leash to a goat with another goat as passenger. The error does produce a stack trace, but does not specify an exception, so it's kind of weird. The main contents of the error message is as follows:
_Entity passenger must match, cannot add {Entity} as passenger of {Entity}_

It's unknown whether the leash is the important bit, but it does not trigger, for example when teleporing a goat as passenger of a furnace minecart.

Produced on paper-1.19-34.jar

An example of the exception:
![](https://cdn.discordapp.com/attachments/853664475021705246/989611167276224512/unknown.png)

**Comment by Thorinwasher** [comment]
I believe that this issue is similar to that of the PoweredMinecart. Somehow a passenger teleported to a different world before its vehicle
