### ISSUE TITLE
Leashed entities are teleported to the spawn instead of the nether

### ISSUE THREAD

**Issue by EpicKnarvik97** [stargate-rewritten/Stargate-Bukkit#228]
When teleporting to a Stargate in the nether from a Stargate in the overworld and holding some entity without passengers in a leash, the entity is teleported to the spawn instead of following the player to the nether.
The same behavior is triggered by going from the nether to the overworld, only that it seems to be teleported to nether's spawn equivalent.

This may be the cause of #226.
There is no stack trace or error thrown.

**Comment by Thorinwasher** [comment]
I can not replicate this when going between dimensions with a lama on a leash in spigot 1.19, paper 1.19-34 or paper 1.18.2-267. Could you give a more detailed explanation on how to replicate?

**Comment by EpicKnarvik97** [comment]
After some more testing, it has been discovered that this behavior sometimes only happens after reloading. In my testing, I reloaded by changing the DEBUG_LEVEL configuration value through SG-Command.

Edit: It seems it sometimes appears consistently, even after restarting, after triggering #226.

The used portals:
![2022-06-24_11 40 03](https://user-images.githubusercontent.com/3597346/175509095-3819b282-7d40-4e06-8493-5950acb33955.png)
![2022-06-24_11 39 51](https://user-images.githubusercontent.com/3597346/175509109-23d302a8-f144-48e7-867d-d1cb1ce79d50.png)

**Comment by EpicKnarvik97** [comment]
After a lot of bug testing, it has been discovered that this problem is caused by a non-vehicle entity being pushed back into the nether portal, and the default teleportation not being properly cancelled.

**Comment by EpicKnarvik97** [comment]
This problem seems to affect END_GATEWAY between the overworld and the end too, and is not fixed by the nether portal fix.

**Comment by EpicKnarvik97** [comment]
Teleporting with a goat or other entity (llama included) on a leash from the end to the overworld works fine (although the entity is kind of teleported into the portal's border and suffocated a bit). The goat is teleported as it should. When teleporting from the overworld to the end however, the goat is pushed into the end gateway and teleported to the overworld spawn.
It seems that for some reason, entity teleportation for gateways only happens when it's located in the end. This behavior is not cancelled.
