### ISSUE TITLE
Leashed creature suffocation

### ISSUE THREAD

**Issue by EpicKnarvik97** [stargate-rewritten/Stargate-Bukkit#231]
When teleporting from the end to the overworld using a Stargate with an END_GATEWAY iris and holding a goat in a leash, the goat is consistently teleporting into the border of the Stargate and suffocated to death. The goat can be saved if the user quicly moves away from the Stargate.

![2022-06-24_15 24 00](https://user-images.githubusercontent.com/3597346/175545117-ae77e07e-25b9-4604-b7bb-01e00fd58550.png)

**Comment by Thorinwasher** [comment]
Solved with #233
