### ISSUE TITLE
Is there a world blacklist now?

### ISSUE THREAD

**Issue by Illusionika** [stargate-rewritten/Stargate-Bukkit#234]
I see the dev version is in development

But I looked at the configuration file and it seems that there is no blacklist features, I want to disabled the create and use in some worlds

Like this:

  #What worlds should the plugin features be disabled in.
  DisabledWorlds:
  - 'example_world'

**Comment by Pheotis** [comment]
Hello!

# Current Per-World Functionality
Per-world functionality is currently handled permission-side (as such, there is currently no config interface)

## Stargate-Level Node Handling:
> _Stargate provides several nodes designed to control any portal interactions which might exit in a specified world:_
- Users with **`sg.use.world.example_world`** set to **`false`** will be unable to use portals that would exit in `example_world`
- Users with **`sg.create.world.example_world`** set to **`false`** will not be able to make portals that exit in `example_world`
- Users with **`sg.destroy.world.example_world`** set to **`false`** will not be able to destroy portals that exit in `example_world`

## Manager-Level Node Handling:
> _Any modern perm manager (such as [LP](https://luckperms.net/)) can handle [SG's nodes](https://github.com/stargate-rewritten/Stargate-Bukkit/blob/91d4475e49d4629f91a46b2ad33c23ca3ece90f2/src/main/resources/plugin.yml#L14-L314) within a per-world context:_
- When **`sg.<node>`** is set to **`false`** within a [context](https://luckperms.net/wiki/Context) of `world=example_world`, the node will be denied to users in that world.

## __**Current (Permission-Based) Solution**__:
Using LP syntax as an example, typing the following four commands would effectively disable `example_world`:
```properties
lp group default permission set sg.use.world.example_world false
lp group default permission set sg.create.world.example_world false
lp group default permission set sg.use false world=example_world
lp group default permission set sg.create false world=example_world
```

# Possible Improvements
## Improved Permission Solution
We would be open to adding a `sg.preset.disable_world.<name>` node that groups those four nodes together.
That would probably help to simplify the process while remaining permission-based.
## Configuration Solution
We would also be open to adding an [advanced key](https://github.com/stargate-rewritten/Stargate-Bukkit/wiki/Configuration-Guide#advanced-configuration-keys) for `disabledWorlds`.
