### ISSUE TITLE
Networks Refactor

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#237]
In the current version of stargate: if the name of a the terminal and central network changes, any portal contained within those will convert into a custom network.

It would be better if the portals would stay in the central or terminal network, when the network changes names in the setting.

**Comment by EpicKnarvik97** [comment]
I think the easiest way to do this is to make the presence of the DEFAULT_NETWORK and TERMINAL_NETWORK flags be the decider of which portals are on the default network or not. The network names of those portals should probably be updated with the new network names on startup.

**Comment by Thorinwasher** [comment]
Yes, that's what I thought as well

**Comment by EpicKnarvik97** [comment]
What happens if there is a portal on the potato network, and then the default network is set to potato. Does the existing portal become a portal on the default network, do we keep it separate somehow, or do we force a name change?

**Comment by Pheotis** [comment]
Currently, we have a similar problem for username/custom networks.
I think we solved that with  bracket types or something.

Having said that, a terminal/default network is much more important than a custom network.
It also opens up potential security implications.

I think the best way here is just to rename the existing network potato1 or something to that effect.

**Comment by Thorinwasher** [comment]
Yea, probably easiest fix for it

**Comment by Thorinwasher** [comment]
From yesterdays talk, the conclusion was to add « » as pointers for default/terminal networks. I have one issue with that, how would this display for interserver default/terminal networks work? 

Solution: use §l for interserver network like §l[§r Name §l]

Where 
```properties
«» = Terminal Networks
[] = Default Networks
{} = Personal Networks
() = Custom Networks
<> = Vacant
```
This solution also allows personal interserver networks :).

Default/terminal network for interserver should connect to the default/terminal network of another server regardless of the setting of name for those networks between servers. 

About implementation, there's having special hardcoded uuids for the two different types of networks (default/terminal), probably the best solution. There's two ways of storing these, either store it only as a flag and have an empty networkname (done kinda in legacy), or we store the uuid as well as a flag.

**Comment by Thorinwasher** [comment]
For creation this following excell table can be used to solve conflicts during creation

![Image](https://user-images.githubusercontent.com/37477983/203172872-a3f613f5-99a7-45d8-83b7-bc453b51809d.png)

**Comment by Thorinwasher** [comment]
To allow the proposed changes on network creation, the scripts similar to the following will need to be implemented

# Case ""
```pascal
IF(sg.default NODE)[!]
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

IF( sg.personal  NODE)
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

```

# Case Name
```pascal
IF GATE HAS FLAG "T"
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

IF NAME == OWN NAME
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

IF {NAME} == Default
  IF HAS PERMISSION 
    DEAL WITH SELECTION OR CREATION AND RETURN
  ELSE
    User.Error.Warn

IF {NAME} == CurrentPlayerName
   IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN
```
# Case {NAME}
```pascal
IF NAME == OWN NAME
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN

ELSE IF NAME == CurrentPlayerName
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN
ELSE
    User.Error.Warn
```
 # Case [NAME]
```pascal
IF {NAME} == Default
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN
ELSE
     User.Error.Warn
```
 # Case (NAME)
```pascal
IF {CUSTOM.<NAME> NODE}
   IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN
ELSE
   User.Error.Warn
```
# Case \<NAME\> OR «NAME»
``` pascal
IF {TERMINAL.NAME.USE NODE}
    IF HAS PERMISSION, DEAL WITH SELECTION OR CREATION AND RETURN
ELSE
    User.Error.Warn
```
