### ISSUE TITLE
Migrator Updates

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#243]
The migrator is out of date as it does not adequately deal with the new module system, the new config layout, etc.

- [x] Update the migrator to be able to get from to the last supported version's config to the current dev build's config
- [x] Update the migrator to be able to handle knarvik configs (within the context of the three modules + sgDynmap)
- [x] Implement a `/sg parity` command that automatically installs stargate-customizations, stargate-mechanics, stargate-integrations, and stargate-dynmap. Only register this command if the migrator has detected a knarvik configuration.
- [x] Update the migrator to add a console nag message about something to the effect of:
> **You are upgrading from a fork with non-standard features**!
> Compatibility modules are required if you used any of the following features:
> [V gates, type-specific sign colouring, dynmap integration, command-based editing]
>
> To automatically install all required modules, type `/sg parity`
> For more information, visit `sgrewritten.org/stargaterevived`.

**Comment by Pheotis** [comment]
NOTE: The most recent TMS identified a load of issues with the existing migrator.
Drakia, Knarvik, and Alpha configs no longer load; this will need to be fixed before the next beta.

**Comment by Pheotis** [comment]
Known migrator problems:

- [x] Relocated gatefiles are not properly moved.
- [x] Pre-legacy gatefiles are not currently implemented.

**Comment by Thorinwasher** [comment]
For the /sg parity command, from what network address' will those files be?

**Comment by Thorinwasher** [comment]
Also do we need another translatable message for that?

Also a permission node

And how long should this command last / be possible to initiate? Should it be possible even if I restart the server, in that case it's going to need another variable to be stored in the database.
