### ISSUE TITLE
[TMS TMP001] Manually specified gate name colours fail to load on migrated lclo.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#248]
When an external plugin is used to make a gate with a colour code in it's name (for example, &3), the plugin appears to strip the colour code as it is unable to handle a section symbol.

![image](https://user-images.githubusercontent.com/49039536/209155694-304c8205-3283-41bb-ada6-80c19bfee2fd.png)

**Comment by Thorinwasher** [comment]
This is a ANSI to utf8 conversion issue
