### ISSUE TITLE
Portal was very picky about where the redstone torch was attatched to

### ISSUE THREAD

**Issue by kittyclaus** [stargate-rewritten/Stargate-Bukkit#260]
I used the lc portal pack so I'm not sure if its a general problem or lc pack issue but the portal was very picky about how the redstone torch was placed. We had the block in the correct area but the portal would only work if it was placed against the block at the base of the portal under the redstone lamp. 

Here is a rough diagram of what I mean:
![image](https://user-images.githubusercontent.com/62353866/210019199-81168471-9ee1-473e-bd31-cdf4b3f66b7f.png)

**Comment by Pheotis** [comment]
Wall blocks should probably be treated as their non-wall counterparts for the sake of convenience (`WALL_` should be interchangeable with ``):

```
*_WALL_SIGN == *_SIGN
*_WALL_HANGING_SIGN == *_HANGING_SIGN
*_WALL_BANNER == *_BANNER
*_CORAL_WALL_FAN == *_CORAL_FAN
*_WALL_HEAD == *_HEAD
*_WALL_TORCH == *_TORCH
WALL_TORCH == TORCH
*_WALL_SKULL ==  *_SKULL
```

**Comment by Thorinwasher** [comment]
I'm halfway through implementing this. Just one question;
If I write `*_WALL_SIGN` should that be interchangeable with `*_SIGN` (and so on)?

**Comment by Pheotis** [comment]
> I'm halfway through implementing this. Just one question;
> If I write `*_WALL_SIGN` should that be interchangeable with `*_SIGN` (and so on)?

Yes, that works probably be the most logical behaviour
