### ISSUE TITLE
Villagers not rendering properly

### ISSUE THREAD

**Issue by kittyclaus** [stargate-rewritten/Stargate-Bukkit#264]
When taking villagers through the portal on a boat, they don't render properly.

https://vimeo.com/785766356

**Comment by Thorinwasher** [comment]
Is this only a thing for villagers?

**Comment by Thorinwasher** [comment]
Reproduced with a villager and a creeper with a distance of: 150 blocks. Could not reproduce within 100 blocks. It probably depends on whether the chunk is loaded by the player or not. Does not seem to be entity dependent (thankfully)

My bet is that this is some kind of bug in bukkit or the minecraft client itself. Similar behavior has been seen when teleporting a player on a boat, so it might be able to be fixed if we add a 1 tick delay to it
