### ISSUE TITLE
Broken `S` Flag on Legacy

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#292]
### Bug Description

On legacy, the `S` flag does not do anything.

### Reproduction Steps

1. Install the latest legacy artefact, running on the most recent purpur.
2. Make three gates as follows:
![2023-05-20_19 41 09](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/c2b97821-4ebf-4cae-8fea-ae34b3151727)

```
Test1
Test2
Net1
S
```

```
Test2
Test1
Net1
S
```

```
Test3
 
 
S
```

Right click on the sign for gate "Test3".

### Desired Behaviour

Legacy versions of stargate are weird insofar as, by default, networked gates are unable to connect to fixed gates.

To get around this behaviour, legacy added the `S` flag, which was intended to override this functionality.

Regardless of gate type, gates with the `S` flag should show themselves to all players with the applicable perms, provided they share a network.

### Observed Behaviour

Unfortunately, this does not happen.
Right-clicking the networked gate's sign to select a destination produces the Destination List Empty error.
![2023-05-20_19 41 33](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/7bdcfdfd-3b5f-4d3b-8ad1-97a7e7e6f82b)

**Comment by EpicKnarvik97** [comment]
This is a problem of differing specification between your Legacy and my fork (which does the same as Pseudoknight's fork). The S flag does what it says in the README. It allows an always-on Stargate to be selectable in the destination list of the Stargate it's pointing to, even if that is a networked Stargate. The S flag is stripped from Stargates that are not always on, so it cannot be used by itself.

**Comment by EpicKnarvik97** [comment]
As this is a problem of specification compatibility, this issue is invalid. If we are to change the specification of the S flag, open a new enhancement issue detailing exactly how the S flag should work for all possible cases.
