### ISSUE TITLE
Configurable String Prepended by Default to Flags Line

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#299]
### Use Case

Circumstances wherein (presumably admin) users most frequently make a specific type of portal.

### Proposed Solution

![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/725370c3-3272-478a-aa94-701be5cd637a)

A hidden core string or a sg-mechanics string (I personally prefer the former)?
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/f48e457f-4724-4448-9765-3b644c94a8d2)

### Additional Context

Potential alternatives:

- A command in SGI that would allow users to set and change their own prepend string.

**Comment by Thorinwasher** [comment]
Added an event which should allow for this in addons
