### ISSUE TITLE
Broken signs fail to repopulate

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#318]
### Bug Description

Breaking the sign fo a stargate deletes the contents of the sign.

### Reproduction Steps

1. Break a sign on a stargate.

### Desired Behaviour

Nothing should happen, the text should be repopulated on the sign.

### Observed Behaviour

Sign regenerates, but ppears blank to everyone.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/36bfbf8c-9dd7-4557-81e9-6586c3bda7b1)

Restarting the server fixes this.

**Comment by Thorinwasher** [comment]
This seems very much like a client side bug to me, are you using viaversion?
