### ISSUE TITLE
Large gate formats are parsed, but not detected.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#333]
### Bug Description

.gate files for large designs load properly, but can not be constructed in game. The only debug output is `[Stargate] [Stargate::createPortal] Control block not registered`

### Reproduction Steps

```
portal-open=END_GATEWAY
portal-closed=AIR
button=STONE_BUTTON
toowner=false
X=SHROOMLIGHT
-=SHROOMLIGHT

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
X......................................X
-......................................-
X..................*...................X
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by EpicKnarvik97** [comment]
There exists a lookup table from material type to gate formats, which is used to reduce the amount of gate designs that need to be fully tested. That specific debug message says that it found no gate formats using the block the sign is attached to as its control block type. This would suggest that the gate was not properly loaded, or at least, not properly registered.

Just in case, does the problem still occur with the fix for #334?

**Comment by EpicKnarvik97** [comment]
I cannot reproduce the problem.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/3597346/215e0f15-6991-40c2-bb7d-b23390810a9c)

**Comment by Pheotis** [comment]
I also can no longer reproduce this on the latest version of legacy.
I am going to assume this was fixed.
