### ISSUE TITLE
The migrator is borked again.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#339]
### Bug Description

Attempting to migrate from the latest legacy, on spigot 1.17.1, to the latest alpha, on paper 1.20.6, results in no portals imported.

### Reproduction Steps

1. Build any portals on the latest legacy running spigot 1.17.1
![2024-06-01_15 18 30](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/9f31fc58-0779-43c4-b568-866d624dba70)

2. Swap out the server jar with the latest paper, and the stargate jar with the latest rewritten alpha.
  (keep the world and the stargate folder the same)

### Desired Behaviour

The legacy portals should migrate to the latest rewrite.

### Observed Behaviour

No portals migrate.

### Trace Logs

[Stargate] Enabling Stargate v1.0.0.16-NIGHTLY-2
[Stargate] Running database migration 0.11.5.5 -> 1.0.0.11
[Stargate] No portals migrated!
[Stargate] Running database migration 1.0.0.11 -> 1.0.0.15
[Stargate] Running database migration 1.0.0.15 -> 1.0.0.16

### Other Information

Windows 11

**Comment by Thorinwasher** [comment]
Seems like the migrator does not parse the confguration option `folders.portalFolder` properly.
