### ISSUE TITLE
NITPICK: Stargate attempts to register a listener for org/bukkit/event/block/TNTPrimeEvent on 1.18.2

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#341]
### Bug Description

When running on spigot 1.18.2, stargate tries to register a listener for org/bukkit/event/block/TNTPrimeEvent, prompting a minor error.

### Reproduction Steps

Start stargate on spigot 1.18.2

### Desired Behaviour

No errors should show up in the log.

### Observed Behaviour

`[Server thread/ERROR]: [Stargate] Plugin Stargate v1.0.0.16-NIGHTLY-2 has failed to register events for class org.sgrewritten.stargate.listener.BlockEventListener because org/bukkit/event/block/TNTPrimeEvent does not exist.`

**Comment by Thorinwasher** [comment]
It would actually disable most behavior for Stargate. For the moment, can we just ignore backwards compatibility with the paper/spigot api?

**Comment by Pheotis** [comment]
Looking into it a bit closer, this is a paper method that was added to spigot in 1.20.
Therefore, this only impacts spigot 1.18.X and spigot 1.19.X
