### ISSUE TITLE
Commands broken on latest nightly.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#344]
### Bug Description

Some commands simply don't do anything.

### Reproduction Steps

1. Start a server on the latest paper with the latest nightly.
2. Type `sg parity`
3. Type `sg about`

### Desired Behaviour

For parity, the modules should download and install.
For about, documentation should be linked.

### Observed Behaviour

Nothing happens (beyond the default command information printout).

### Other Information

Running on windows with nightly 3.

**Comment by Thorinwasher** [comment]
Do you have enough perms to perform the commands?

**Comment by Pheotis** [comment]
Yes. This issue also recurs as console.
