### ISSUE TITLE
Liquid portal frames are updatable.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#350]
### Bug Description

Really stupid portals can be broken with block updates.

### Reproduction Steps

1. Make a really stupid portal with fluids in the frame.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/68151da7-309b-455d-9d78-d734408bdbc5)
2. Place fluid, or a block, beside the frame.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/a17d231f-a002-4af7-b0a1-f1092a33fe34)

### Desired Behaviour

The portal should not be destroyed.

### Observed Behaviour

The portal is destroyed.

**Comment by Thorinwasher** [comment]
I can not reproduce with portal parts changing state in the latest version of paper. But I can reproduce liquids going out of the portal, which should not be the case.

Could it be that the corners are not part of the gate in this scenario?
