### ISSUE TITLE
The H flag is borked.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#359]
### Bug Description

The H flag has no noticable effect on portals.

### Reproduction Steps

```
portal1

network

```
```
portal2

network

```
```
portal3

network
h
```

### Desired Behaviour

For non opped users

Scrolling portal 1: [2]
Scrolling portal 2: [1]
Scrolling portal 3: [1, 2]

### Observed Behaviour

For non opped users

Scrolling portal 1: [2, 3]
Scrolling portal 2: [1, 3]
Scrolling portal 3: [1, 2]

### Trace Logs

Latest version of core, with all addons, with latest paper.

**Comment by Pheotis** [comment]
Also, I can not test this (because H flags are borked), but I remember the S flag being broken as well.
Given that the S flag is closely related to the H flag, I'll combine it into this issue:

```
1

net

```
```
2

net

```
```
3

net
h
```
```
4

net
s
```

Visibility:
1: [2, 4]
2: [1, 4]
3: [1, 2, 4]
4: [1, 2, 3]

**Comment by Thorinwasher** [comment]
We moved the H, N and S flag to Stargate Mechanics. Could that affect anything?

(This should really be an stargate mechanics issue)

**Comment by Pheotis** [comment]
Whoops!

**Comment by Thorinwasher** [comment]
> Also, I can not test this (because H flags are borked), but I remember the S flag being broken as well. Given that the S flag is closely related to the H flag, I'll combine it into this issue:
> 
> ```
> 1
> 
> net
> ```
> 
> ```
> 2
> 
> net
> ```
> 
> ```
> 3
> 
> net
> h
> ```
> 
> ```
> 4
> 
> net
> s
> ```
> 
> Visibility: 1: [2, 4] 2: [1, 4] 3: [1, 2, 4] 4: [1, 2, 3]

What exactly is wrong with the `S` flag here? The behavior described seems to me to be expected behavior; every portal in the network will be listed if the origin portal has the `S` flag.

**Comment by Pheotis** [comment]
> > Also, I can not test this (because H flags are borked), but I remember the S flag being broken as well. Given that the S flag is closely related to the H flag, I'll combine it into this issue:
> > ```
> > 1
> > 
> > net
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 2
> > 
> > net
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 3
> > 
> > net
> > h
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 4
> > 
> > net
> > s
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Visibility: 1: [2, 4] 2: [1, 4] 3: [1, 2, 4] 4: [1, 2, 3]
> 
> What exactly is wrong with the `S` flag here? The behavior described seems to me to be expected behavior; every portal in the network will be listed if the origin portal has the `S` flag.

The behaviour described is indeed the expected behaviour; I just don't know if that is the behaviour that actually occurs. If this is indeed the behaviour that occurs, there is nothing wrong with the S flag.

**Comment by Thorinwasher** [comment]
> The behaviour described is indeed the expected behaviour; I just don't know if that is the behaviour that actually occurs. If this is indeed the behaviour that occurs, there is nothing wrong with the S flag.

Okay, then it's fixed
