### ISSUE TITLE
Waterloggable portal frames enable unauthorized destruction.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#361]
### Bug Description

Users without permission to break stargates can place blocks in waterloggable frames, thus breaking the gate.

### Reproduction Steps

Make a stupid portal and frame.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/09b462aa-ed9f-471f-a4cb-1f17f71121d2)

### Desired Behaviour

The frame should be protected from people placing waterloggable blocks.

### Observed Behaviour

People can place waterloggable blocks, breaking the portal as a result.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/6054d497-ae12-46e1-9b0f-e22c1b4aa781)

### Trace Logs

Latest core, modules, paper.

**Comment by Thorinwasher** [comment]
You placed it in the corner, are you sure that is part of the gate design? (can not reproduce)
