### ISSUE TITLE
`I` gates do not update.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#366]
### Bug Description

This is probably related to #261

### Reproduction Steps

1. Make this portal on Server1:
```
gate1
gate2
server2
i
```
> This will create a disconnected sign because gate2 doesn't exist yet.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/5dec8fc9-cca7-4fbb-9dec-71fec2108c70)

2. Make this portal on Server2:
```
gate1
gate2
server2
i
```
> This will create a connected gate because gate1 was just created
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/957158c6-1a60-4187-9c0a-3bfc0056870d)

3. Return to Server1 and try to use gate1.
> This will still be disconnected.
![image](https://github.com/stargate-rewritten/Stargate-Bukkit/assets/49039536/5dec8fc9-cca7-4fbb-9dec-71fec2108c70)

### Desired Behaviour

Somehow, we need to inform `gate1` on `server1` that its destination has been created

### Observed Behaviour

An incorrectly disconnected portal occurs.

### Trace Logs

Latest core, latest paper, latest velocity, via mariadb on windows.

**Comment by Pheotis** [comment]
I still do not understand how to reliably repro this (it happens frequently, but with no apparent pattern).
In any case, messing around with I gates on a velocity mariadb network of paper servers is bound to produce this problem in abundance.

**Comment by Thorinwasher** [comment]
What proxy software did you use?

**Comment by Thorinwasher** [comment]
`Personal1` is not an interserver portal, if that were the case, you would see the text like **this**
