### ISSUE TITLE
Entity collision can cause the player to enter the destination portal (Cross server/world)

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#370]
### Bug Description

Going through a boat in a U gate causes the player to go to another server, the boat to remain on the original server, and the player to get bumped back into the portal if they return.

### Reproduction Steps

See [this comment](https://discord.com/channels/853659042799026177/853662140619948053/1249172409442107532) (reported on discord).

1. Make two U gates across different servers.
2. Go through one in a boat
3. Return to the origin server

### Desired Behaviour

The user should not get shoved back into the U gate, no matter what obstructions are in its way.

Could probably either prevent entity knockback/pushing within a small radius of a gate, or perhaps try to move blocking entities away from the gate whenever someone enters from another server?

### Observed Behaviour

The boat bumps the user back into the U gate.

### Other Information

Latest nightly on paper 1.20.6

**Comment by Thorinwasher** [comment]
We could just temporarily disable collisions on the player

This seems like it would be an issue for normal gates as well
