### ISSUE TITLE
Possible compat issue between stargate and myworlds.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#382]
Per a discord support conversation.
This issue will be updated when I get back to my computer.

ArcLight 1.20.1
Myworlds, stargate.

Impacts legacy and nightly?
Only impacts nether-portal irises.

https://youtu.be/7p_olB8NQqU

**Comment by Thorinwasher** [comment]
Can not reproduce on arclight arclight-fabric-1.20.4-1.0.4-80ec5df

I therefore recomend using that version instead, this seems like a bug in arclight

**Comment by Pheotis** [comment]
I also CNR this, probably fixed in latest versions.
Can be reopened if this is not the case.
