### ISSUE TITLE
Add API for getting all portals and getting portal flags

### ISSUE THREAD

**Issue by Ghost-chu** [stargate-rewritten/Stargate-Bukkit#49]
I'm creating Stargate addon - https://github.com/Bilicraft-Community/StargateDynmap, but while I trying to get all portals and portal flags, I have noticed there no API for it, so sadly I must use reflect to calling internal fields/functions.

So if there can add some useful API, maybe it can make life better :).

**Comment by Thorinwasher** [comment]
The rewrite pretty much have a fully fletched API, so I guess I can close this
