### ISSUE TITLE
Creation of Stargate API

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#77]
The official StarGate API, with the primary goal of facilitating [add-on development](https://github.com/orgs/stargate-bukkit/projects/1) and integration with other plugins.

Note that this is in addition to methodscript support, which can be found [here](https://github.com/stargate-bukkit/SG-MethodScript).

Current Requirements (feel free to comment with additional suggestions):
- Modify portals
  - Change network
  - Change names
  - Change owners
  - Change portal types
  - Change portal flags.
- Create new portals
  - Force-generate portals from nothing.
- Destroy portals
- Get comprehensive information about portals.

**Comment by Pheotis** [comment]
Upon merging to main, this issue will resolve #49

**Comment by Pheotis** [comment]
Other things that would be useful for the api to do (to be edited later)

- find information about all portals in a given area and/or world
-

**Comment by EpicKnarvik97** [comment]
- Need to be able to change configuration values if SGCommand's /config command is to work properly. Changed configuration values should be loaded immediately.
- Need to be able to get permission information if add-ons are to be able to check permissions before performing potentially destructive tasks.
- Need to have access to the gate layout parser and saver if plugins should be able to generate gate files given some selection. Also need public access to which characters are used for the frame/iris/control blocks,

**Comment by Pheotis** [comment]
The API should also be able to support the functionality needed by existing addons.

For [Dynmap](https://github.com/stargate-rewritten/SG-Dynmap), the list is on this issue: #49 .
For [Methodscript](https://github.com/stargate-rewritten/SG-MethodScript), the list is on this issue: stargate-rewritten/SG-MethodScript#1

**Comment by Pheotis** [comment]
Version one of the API is now done.
