### ISSUE TITLE
Support for the other proxies.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#95]
Currently, we support bungeecord and its forks.
Eventually, we should probably support velocity.

**Comment by Thorinwasher** [comment]
Update on this, velocity uses a different protocol. Current solution does not work for velocity

**Comment by Pheotis** [comment]
The plugin now works through velocity if the [BungeeBark Velocity Plugin](https://github.com/RoinujNosde/BungeeBark) is enabled.

BungeeBark's modrinth page may be found [here](https://modrinth.com/plugin/bungeebark); for now, we will use it as a soft dependency.
We will also maintain BungeeBark as may be needed until we get around to adding native support for velocity.
