### ISSUE TITLE
"animated" blocks - Block changes for open and closed

### ISSUE THREAD

**Issue by Tabletopcheese** [stargate-rewritten/Stargate-Bukkit#98]
X= STONE (when off)
X= Glowstone (When on)

Basically give another block a state like the portal blocks have. (open/closed)

or for a better example, redstonelamp on/off - Would show the portal activating.

**Comment by Pheotis** [comment]
It has been decided that, should animated customisations be a feature, they would probably be best situated within the Stargate Customizations module.

For that reason, I'm going to close this issue and instead track animation-related features as https://github.com/stargate-rewritten/Stargate-Customizations/issues/13
